### ISSUE TITLE
Tool rack

### ISSUE THREAD

**Issue by posics** [viesturz/TapChanger-lite#1]
Maybe atrach the "tool rack" (the 2020 section on which all tool heads hang) to the front of the y-axis (just redesign front 2 belt idlers) so you don't have to make z moves to change tools?

**Comment by viesturz** [comment]
Hmm, can you give a link? Not familiar with a tool rack from 2020

**Comment by viesturz** [comment]
Oh, got it. You mean the front extrusion where tools are mounted.

That would completely lock the z movement, but about 15mm Z shift is required to mount/ unmount the tools.
Also may be too heavy for the motor friction to hold them in place when not powered

If you have some mechanism in mind that would work horizontally without extra servos and still preserve Tap funcionality, might be worth exploring.

**Comment by mggevaer** [comment]
DISCLAIMER: I have not looked at the mechanism too much.

Maybe the mechanism can be turned sideways 90 degrees? So that rather than 15mm Z shift it would be 15 mm X shift?
Prusa XL uses a sideways movement as it is a trident-style printer without flying gantry.

That being said, some insights(maybe even mods?) into increasing z-speed would also decrease tool change time, and not require a rework of the existing design.
It would also not increase the weight of the gantry like mounting the toolheads on the front of the gantry would.

**Comment by viesturz** [comment]
I think it's not a problem anymore: https://youtu.be/S-om0MPE5qI

**Comment by mggevaer** [comment]
I'll say! Completely removes the need for any other complicated solutions!
